name: speak_together
description: 함께 말해요 토끼와 거북이

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
    flutter_launcher_icons: ^0.11.0
    audioplayers: ^1.1.1
    video_player: ^2.4.7
    characters: ^1.1.0
    korea_regexp: ^0.2.0+3



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
      # images
      - assets/images/a.jpeg
      - assets/images/b.png
      - assets/images/i.jpeg
      - assets/images/n.png
      - assets/images/black.jpeg
      - assets/images/test_image.png
      - assets/images/butterfly.jpeg
      - assets/images/forest.jpg
      - assets/images/logo.jpeg
      - assets/images/rabbit.jpeg
      - assets/images/rabbitturtle.jpeg
      - assets/images/speakBall.jpeg
      - assets/images/speakBall2.jpeg
      - assets/images/turtle.jpeg
      - assets/images/forest_blur.jpeg
      - assets/images/2_뛰다.png
      - assets/images/2_뛰다 1.png
      - assets/images/_뛰다.png
      - assets/images/가마솥.png
      - assets/images/거북이.png
      - assets/images/걱정아이들.png
      - assets/images/곰.png
      - assets/images/구렁이.png
      - assets/images/구름.png
      - assets/images/금은보화.png
      - assets/images/기다_거북이.png
      - assets/images/기쁘다_거북이.png
      - assets/images/끓는솥.png
      - assets/images/나무.png
      - assets/images/나무흔들.png
      - assets/images/나비.png
      - assets/images/놀란_부부.png
      - assets/images/놀란아이들.png
      - assets/images/다친제비.png
      - assets/images/도깨비와_방망이.png
      - assets/images/도망가다_늑대.png
      - assets/images/돼지1.png
      - assets/images/돼지2.png
      - assets/images/돼지3.png
      - assets/images/돼지4.png
      - assets/images/둘째의_판자집.png
      - assets/images/둥지.png
      - assets/images/무서워하는_-놀부.png
      - assets/images/바람.png
      - assets/images/바람부는_-늑대.png
      - assets/images/박열매.png
      - assets/images/벽돌.png
      - assets/images/부수는__늑대.png
      - assets/images/부엌.png
      - assets/images/뺨.png
      - assets/images/뺨때리다.png
      - assets/images/새.png
      - assets/images/선_돼지.png
      - assets/images/숨은__돼지.png
      - assets/images/시작.png
      - assets/images/앉은_돼지.png
      - assets/images/언덕.png
      - assets/images/언덕위.png
      - assets/images/엄마돼지.png
      - assets/images/울다토끼.png
      - assets/images/자다_토끼.png
      - assets/images/주걱.png
      - assets/images/집_창문굴뚝문.png
      - assets/images/집이_모두_무너졌어요.png
      - assets/images/짚으로_만든_집.png
      - assets/images/초가집.png
      - assets/images/토거1.png
      - assets/images/토거2.png
      - assets/images/토거3.png
      - assets/images/토거4.png
      - assets/images/튜토1.png
      - assets/images/튜토2.png
      - assets/images/튜토3.png
      - assets/images/튜토4.png
      - assets/images/튜토5.png
      - assets/images/튜토6.png
      - assets/images/하늘.png
      - assets/images/형제.png
      - assets/images/흥부1.png
      - assets/images/흥부2.png
      - assets/images/흥부3.png
      - assets/images/흥부4.png
      - assets/images/ㄱ.png
      - assets/images/ㄴ.png
      - assets/images/ㄷ.png
      - assets/images/ㄹ.png
      - assets/images/ㅁ.png
      - assets/images/ㅂ.png
      - assets/images/ㅅ.png
      - assets/images/ㅇ.png
      - assets/images/ㅈ.png
      - assets/images/ㅊ.png
      - assets/images/ㅋ.png
      - assets/images/ㅌ.png
      - assets/images/ㅍ.png
      - assets/images/ㅎ.png
      - assets/images/ㅏ.png
      - assets/images/ㅑ.png
      - assets/images/ㅓ.png
      - assets/images/ㅕ.png
      - assets/images/ㅗ.png
      - assets/images/ㅛ.png
      - assets/images/ㅜ.png
      - assets/images/ㅠ.png
      - assets/images/ㅡ.png
      - assets/images/ㅣ.png
      - assets/images/ㅐ.png
      - assets/images/ㅔ.png
      - assets/images/ㅒ.png
      - assets/images/ㅖ.png
      - assets/images/ㄲ.png
      - assets/images/ㄸ.png
      - assets/images/ㅆ.png
      - assets/images/ㅃ.png
      - assets/images/ㅉ.png
      - assets/images/ㅙ.png

      # sounds
      - assets/sounds/test.mp3
      - assets/sounds/rabbit_read.wav
      - assets/sounds/rabbit_speak.wav
      - assets/sounds/rabbit_story1_1.wav
      - assets/sounds/rabbit_story1_2.wav
      - assets/sounds/rabbit_story1_3.wav
      - assets/sounds/rabbit_story1_4.wav
      - assets/sounds/rabbit_story2_1.wav
      - assets/sounds/rabbit_story2_2.wav
      - assets/sounds/rabbit_story2_3.wav
      - assets/sounds/rabbit_story2_4.wav
      - assets/sounds/rabbit_story3_1.wav
      - assets/sounds/rabbit_story3_2.wav
      - assets/sounds/rabbit_story3_3.wav
      - assets/sounds/rabbit_story3_4.wav
      - assets/sounds/turtle_out.wav
      - assets/sounds/turtle_read.wav
      - assets/sounds/turtle_speak.wav
      - assets/sounds/turtle_story1_1.wav
      - assets/sounds/turtle_story1_2.wav
      - assets/sounds/turtle_story1_3.wav
      - assets/sounds/turtle_story1_4.wav
      - assets/sounds/turtle_story2_1.wav
      - assets/sounds/turtle_story2_2.wav
      - assets/sounds/turtle_story2_3.wav
      - assets/sounds/turtle_story2_4.wav
      - assets/sounds/turtle_story3_1.wav
      - assets/sounds/turtle_story3_2.wav
      - assets/sounds/turtle_story3_3.wav
      - assets/sounds/turtle_story3_4.wav
      - assets/sounds/tutorial1.wav
      - assets/sounds/tutorial2.wav
      - assets/sounds/tutorial3.wav
      - assets/sounds/tutorial4.wav
      - assets/sounds/tutorial5.wav
      - assets/sounds/tutorial6.wav
      - assets/sounds/start_theme.mp3
      - assets/sounds/main_theme.mp3
      - assets/sounds/main_slow_theme.mp3

      # videos
      - assets/videos/butterfly_test.mp4
      - assets/videos/rabbit_bakseed.mp4
      - assets/videos/rabbit_bat.mp4
      - assets/videos/rabbit_bbaym.mp4
      - assets/videos/rabbit_bear.mp4
      - assets/videos/rabbit_bird.mp4
      - assets/videos/rabbit_block.mp4
      - assets/videos/rabbit_block_tuntun.mp4
      - assets/videos/rabbit_brother.mp4
      - assets/videos/rabbit_cloud.mp4
      - assets/videos/rabbit_down.mp4
      - assets/videos/rabbit_drop.mp4
      - assets/videos/rabbit_dungjy.mp4
      - assets/videos/rabbit_fast.mp4
      - assets/videos/rabbit_flower.mp4
      - assets/videos/rabbit_forest.mp4
      - assets/videos/rabbit_ggaeby.mp4
      - assets/videos/rabbit_heungbu_good.mp4
      - assets/videos/rabbit_heungbu_nolbu.mp4
      - assets/videos/rabbit_hide.mp4
      - assets/videos/rabbit_house.mp4
      - assets/videos/rabbit_house_break.mp4
      - assets/videos/rabbit_jaeby.mp4
      - assets/videos/rabbit_jip.mp4
      - assets/videos/rabbit_jip_blow.mp4
      - assets/videos/rabbit_juguk.mp4
      - assets/videos/rabbit_kitchen.mp4
      - assets/videos/rabbit_light.mp4
      - assets/videos/rabbit_many.mp4
      - assets/videos/rabbit_new_house.mp4
      - assets/videos/rabbit_oneyear.mp4
      - assets/videos/rabbit_ouside.mp4
      - assets/videos/rabbit_out.mp4
      - assets/videos/rabbit_pig.mp4
      - assets/videos/rabbit_outside.mp4
      - assets/videos/rabbit_pleasure.mp4
      - assets/videos/rabbit_poor.mp4
      - assets/videos/rabbit_rabbit.mp4
      - assets/videos/rabbit_rabbit_run.mp4
      - assets/videos/rabbit_rice.mp4
      - assets/videos/rabbit_run.mp4
      - assets/videos/rabbit_runout.mp4
      - assets/videos/rabbit_sad.mp4
      - assets/videos/rabbit_seed.mp4
      - assets/videos/rabbit_sky.mp4
      - assets/videos/rabbit_sleep.mp4
      - assets/videos/rabbit_slow.mp4
      - assets/videos/rabbit_snake.mp4
      - assets/videos/rabbit_sot.mp4
      - assets/videos/rabbit_ssadta.mp4
      - assets/videos/rabbit_start.mp4
      - assets/videos/rabbit_summer.mp4
      - assets/videos/rabbit_summergo.mp4
      - assets/videos/rabbit_treasure.mp4
      - assets/videos/rabbit_tree.mp4
      - assets/videos/rabbit_tree_down.mp4
      - assets/videos/rabbit_tuntun.mp4
      - assets/videos/rabbit_turtle.mp4
      - assets/videos/rabbit_turtle_ungun.mp4
      - assets/videos/rabbit_turtle_win.mp4
      - assets/videos/rabbit_unduck.mp4
      - assets/videos/rabbit_unduck_up.mp4
      - assets/videos/rabbit_up.mp4
      - assets/videos/rabbit_walk.mp4
      - assets/videos/rabbit_wall.mp4
      - assets/videos/rabbit_wind.mp4
      - assets/videos/rabbit_windblow.mp4
      - assets/videos/rabbit_window.mp4
      - assets/videos/rabbit_wolf.mp4
      - assets/videos/rabbit_you.mp4
      - assets/videos/rabbit_gulttuk.mp4
      - assets/videos/rabbit_rabbit_lose.mp4
      - assets/videos/rabbit_jaeby_leg.mp4
      - assets/videos/turtle_baby.mp4
      - assets/videos/turtle_bak.mp4
      - assets/videos/turtle_bakseed.mp4
      - assets/videos/turtle_bat.mp4
      - assets/videos/turtle_bbaym.mp4
      - assets/videos/turtle_bear.mp4
      - assets/videos/turtle_bird.mp4
      - assets/videos/turtle_block.mp4
      - assets/videos/turtle_brother.mp4
      - assets/videos/turtle_cloud.mp4
      - assets/videos/turtle_down.mp4
      - assets/videos/turtle_drop.mp4
      - assets/videos/turtle_dungjy.mp4
      - assets/videos/turtle_fast.mp4
      - assets/videos/turtle_flower.mp4
      - assets/videos/turtle_flyout.mp4
      - assets/videos/turtle_ggaeby.mp4
      - assets/videos/turtle_gulttuk.mp4
      - assets/videos/turtle_heongbu_nolbu.mp4
      - assets/videos/turtle_heungbu_good.mp4
      - assets/videos/turtle_hide.mp4
      - assets/videos/turtle_house.mp4
      - assets/videos/turtle_house_break.mp4
      - assets/videos/turtle_jaebi_leg.mp4
      - assets/videos/turtle_jaeby.mp4
      - assets/videos/turtle_jip.mp4
      - assets/videos/turtle_jip_flyout.mp4
      - assets/videos/turtle_juguk.mp4
      - assets/videos/turtle_kitchen.mp4
      - assets/videos/turtle_light.mp4
      - assets/videos/turtle_many.mp4
      - assets/videos/turtle_new_house_build.mp4
      - assets/videos/turtle_oneyear.mp4
      - assets/videos/turtle_out.mp4
      - assets/videos/turtle_outside.mp4
      - assets/videos/turtle_pig.mp4
      - assets/videos/turtle_pleasure.mp4
      - assets/videos/turtle_poor.mp4
      - assets/videos/turtle_rabbit_lose.mp4
      - assets/videos/turtle_rabbit_run.mp4
      - assets/videos/turtle_rice.mp4
      - assets/videos/turtle_run.mp4
      - assets/videos/turtle_runout.mp4
      - assets/videos/turtle_sad.mp4
      - assets/videos/turtle_seed.mp4
      - assets/videos/turtle_sky.mp4
      - assets/videos/turtle_sleep.mp4
      - assets/videos/turtle_slope.mp4
      - assets/videos/turtle_slow.mp4
      - assets/videos/turtle_snake.mp4
      - assets/videos/turtle_sot.mp4
      - assets/videos/turtle_springout.mp4
      - assets/videos/turtle_ssadta.mp4
      - assets/videos/turtle_start.mp4
      - assets/videos/turtle_summer.mp4
      - assets/videos/turtle_this_block_tuntun.mp4
      - assets/videos/turtle_treasure.mp4
      - assets/videos/turtle_tree.mp4
      - assets/videos/turtle_tree_down.mp4
      - assets/videos/turtle_tuntun.mp4
      - assets/videos/turtle_turtle.mp4
      - assets/videos/turtle_turtle_ungum.mp4
      - assets/videos/turtle_turtle_win.mp4
      - assets/videos/turtle_unduck.mp4
      - assets/videos/turtle_unduck_uo.mp4
      - assets/videos/turtle_up.mp4
      - assets/videos/turtle_walk.mp4
      - assets/videos/turtle_wall.mp4
      - assets/videos/turtle_wind.mp4
      - assets/videos/turtle_window.mp4
      - assets/videos/turtle_wolf.mp4
      - assets/videos/turtle_you.mp4
      - assets/videos/turtle_butterfly.mp4
      - assets/videos/turtle_rabbit.mp4
      - assets/videos/turtle_forest.mp4


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

rules:
  prefer_typing_uninitialized_variables: false
  prefer_const_constructors_in_immutables: false
  prefer_const_constructors: false
  avoid_print: false